# Generated by Django 5.2.8 on 2025-12-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='сумма выплаты')),
                ('currency', models.IntegerField(choices=[(643, 'RUB'), (840, 'USD'), (978, 'EUR')], default=643, verbose_name='валюта')),
                ('recip_details', models.TextField(verbose_name='реквизиты получателя')),
                ('status', models.IntegerField(choices=[(1, 'OPENED'), (2, 'APPROVED')], default=1, verbose_name='статус заявки')),
                ('description', models.TextField(blank=True, verbose_name='описание или комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка на выплату',
                'verbose_name_plural': 'Заявки на выплату',
                'ordering': ['id'],
            },
        ),
    ]
